import Head from "next/head";
import styles from "../styles/Home.module.css";
import Header from "../components/header";
import Landing from "../components/landing";
import Slider from "../components/slider";
import Footer from "../components/footer";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Recruitment Startup</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <Header />
        <Landing />
        <Slider />
        <Footer />
      </div>
    </div>
  );
}
